
spring:
  cloud:
    vault:
      enabled: false
  datasource:
    url: "jdbc:mariadb://localhost:3306/YOURDATABASE?user=YOURUSERNAME&password=YOURPASSWORD" # TODO: update with your own database information, at a minimum update the YOURDATABASE, YOURUSERNAME, YOURPASSWORD